### ISSUE TITLE
Group pages and capture more information

### ISSUE THREAD

**Issue by chaoran-chen** [loculus-project/loculus#1123]
- [x] Capture more information when a user creates a group: contact email address and information about the organization (@corneliusroemer, what do we need for ENA submission?)
  - [x] #1127 
  - [x] #1156 
- [x] A group page for members similar to 
![image](https://github.com/loculus-project/loculus/assets/18666552/dcf82a8d-f715-4f85-933f-e78826e8c51b)
- [x] A group page for non-members that is linked from the sequence details pages similar to 
![image](https://github.com/loculus-project/loculus/assets/18666552/705894d5-08bf-466e-88ca-7e2a45002866)
