### ISSUE TITLE
Allow editing group contact information through website

### ISSUE THREAD

**Issue by theosanderson** [loculus-project/loculus#2258]
As a group member I want to update group information to keep group information up to date and correct in case of changes.

## Acceptance Criteria

There is an edit group button that leads to an edit UI where all the group info can be edited and there is 'save changes' button to save the changes.
Group info can only be edited by members of the group.

There are unit tests for the backend.

## Tasks

- [ ] Update the backend to include a new `PUT /groups/<id>` endpoint to update group information.
- [ ] Add tests for the backend.
- [ ] ensure that only group members can edit the group.
- [ ] Update the UI to include an _edit_ button on a group and a new `/group/<id>/edit` endpoint with a new edit form based on the _new group_ form.

**Comment by fhennig** [comment]
I'm gonna get started on this, I've updated the issue description with more info from a refinement call I had with @corneliusroemer
