### ISSUE TITLE
Automated flagging of dubious sequences

### ISSUE THREAD

**Issue by theosanderson** [loculus-project/loculus#2346]
We want to be able to flag questionable sequences

              We also may not have captured in issues @emmahodcroft's (and the rest of us)'s concept around flagging "dubious" sequences

_Originally posted by @theosanderson in https://github.com/loculus-project/loculus/issues/1272#issuecomment-1986219631_

After handling manual flagging of sequences in: https://github.com/loculus-project/loculus/issues/813 we should move to this more automated flagging, which would probably come from the preprocessing pipeline
- [ ] Add preprocessing warnings/flags to sequence page: https://github.com/loculus-project/loculus/issues/1272
- [ ] Warn if we suspect sequence data is wrong
- [ ] Warn if we suspect sequence data is filled with reference
- [ ] Warn if we suspect sequence data lab adapted strain

**Comment by chaoran-chen** [comment]
Changing the labels as it is not very refined and probably not that of a high priority given that we haven't worked on it since it has been created over half an year ago.
