### ISSUE TITLE
Curators flagging sequence as 'having issues' manually

### ISSUE THREAD

**Issue by theosanderson** [loculus-project/loculus#813]
There is a concept that curators can mark a sequence as having issues, which will allow them to be excluded from search. We need to figure out what we need to do for this in technical terms. It essentially involves a metadata item that can be manually changed outside the version-system by super-users.

Required steps: 
- [ ] We maintain a list of problematic sequences on GitHub E.g., a TSV with a comment column or in the backend? (could be added using external metadata implementation -> probably need a new endpoint?)
- [ ] Add a "is_flagged" flag to the data.
- [ ] To set the flag in an emergency, we can "manually" change the preprocessed data.
- [ ] Allow users to filter by is_flagged on the website in search and download queries

## Acceptance criteria

- You can configure a TSV file URL in the pipeline (the TSV has the columns: accessionVersion, comment).
- In the pipeline output, flagged sequences are marked as such, i.e. there are two new field "isFlagged = true" and the comment

**Comment by emmahodcroft** [comment]
We also then need to add something to the search interface to exclude (default: on) or include such sequences in searches. Possibly also something showing how many sequences would fit the current query but are excluded due to being 'flagged'? (that's a bonus though)

**Comment by chaoran-chen** [comment]
@fhennig and I just added some acceptance criteria to the initial message and created a new ticket #3306 for configuring the default search.
